language: python

python:
  - "3.7"
  - "3.6"
  - "3.5"

# command to install dependencies
install:

  # install dcmtk dependencies necessary for the decompression() function
  - sudo apt-get update
  - sudo apt-get install python3-dev
  - sudo apt-get install unixodbc-dev
  - sudo apt-get install -y dcmtk
  - sudo apt-get install -y orthanc
  - sudo apt-get install python-dev graphviz libgraphviz-dev pkg-config
  - wget https://github.com/rordenlab/dcm2niix/releases/download/v1.0.20181125/dcm2niix_25-Nov-2018_lnx.zip
  - ls -lasth
  - unzip dcm2niix_25-Nov-2018_lnx.zip
  - export PATH=$PATH:$(pwd)

  # install Python dependencies
  - pip install -r requirements.txt

# command to run tests
script:
  - cd "Python" # pytest MUST BE initiaited from the python folder.
  - python -m pytest -s --cov # Run test with automated coverage reporting
  
# After successful test, run coverage and send data to Coverall
after_success:  
  - ls -lah # list the files in the root dir # Used to check voerage file generation
  - coveralls -d ./.coverage # Ask coverall to send the coverage file generated to coverall
  