language: python

python:
  - "3.6"
# command to install dependencies

install:
  - pip install -r requirements.txt
# command to run tests

script:
  - pytest
  # - nosetests --with-coverage

after_success:
  - coverage run ./Python/Coverage/coverage_setup.py  
  - coverage report -m
  - coveralls --rcfile=./Python/.coveragerc

notifications:
	slack: neonatalbrainplatform:GFWHNXeNtYI7PnecsXOR1eNt