language: python

python:
  - "3.6"

# command to install dependencies
install:
  
  # install Python dependencies
  - pip install -r requirements.txt

  # install dcmtk dependencies necessary for the decompression() function
  - sudo apt-get update
  - sudo apt-get install -y dcmtk
  - sudo apt-get install -y orthanc
  - sudo apt-get install -y sshpass

# command to run tests
script:
  - cd "Python"
  - python -m pytest -s --cov # Run test with automated coverage reporting
  
# After successful test, run coverage and send data to Coverall
after_success:  
  - coverage report -m # Run Coverage report
  - ls -lah # list the files in the root dir # Used to check voerage file generation
  - coveralls -d ./.coverage # Ask coverall to send the coverage file generated to coverall
  