language: python

python:
  - "3.6"
# command to install dependencies

install:
  - pip install -r requirements.txt
# command to run tests

script:
  - cd "Python"
  - python -m pytest
  # - nosetests --with-coverage

after_success:
  - coverage run ./Coverage/coverage_setup.py  # Run Coverage
  - coverage report -m # Run Coverage report
  - ls -lmh # list the files in the root dir # Used to check voerage file generation
  - coveralls -d ./.coverage # Ask coverall to send the coverage file generated to coverall