     # This is the selenium image (i.e. worker node) that will run the actual work process which is executed to setup the bridge connection between the database and the front end user interaction
    chrome:
        image: selenium/node-chrome-debug:3.14.0-gallium
        volumes:
            - /dev/shm:/dev/shm
        depends_on:
            - hub
            - loris
            - lorisdb
        environment:
            HUB_HOST: hub
            HUB_PORT: 4444
        entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'
        networks:
            - backend

    # The hub is HARDCODED to be recognized in subroutines as "hub" DO NOT CHANGE THIS NAME.
    hub:
        image: selenium/hub:3.14.0-gallium
        depends_on:
            - loris
            - lorisdb
        ports:
            - "4444:4444"
        networks:
            - backend

    lorisdbsetup:

        build:
            context: ../..
            dockerfile: DockerBuilds/22/Dockerfile.LORIS${LORIS_version}.dbsetup
            args:
                - ARGS_MySQLHost=${MySQLHost}
                - ARGS_MySQLRoot=${MySQLRoot}
                - ARGS_ProjectName=${ProjectName}
                - ARGS_MySQLRootPassword=${MySQLRootPassword}
                - ARGS_MySQLUser=${MySQLUser}
                - ARGS_MySQLUserPassword=${MySQLUserPassword}
                - ARGS_LorisFrontendUser=${LorisFrontendUser}
                - ARGS_LorisFrontendPassword=${LorisFrontendPassword}
                - ARGS_Ext_Port_HTTP=${Ext_Port_HTTP}
                - ARGS_Ext_URL=${Ext_URL}
                #- ARGS_LorisMaintenanceEmail=${LorisMaintenanceEmail}
                - ARGS_MySQLDatabase=${MySQLDatabase} # the database created by default is called LORIS
            # Environment not specified as the DockerFile is suppose to be standalone and workable too .
        # Where to push eventually.
        image: neonatalbrainplatform/lorisdbsetup:${LORIS_version}
        depends_on: # all these need to be up and running before running the Selenium integrator.
            - loris
            - lorisdb
            - hub
            - chrome
        networks:
            - backend